name: Build KDE Daemon (kded)

on:
  push:
    branches:
      - main  # or your working branch
  pull_request:
    branches:
      - main  # or your working branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ extra-cmake-modules qtbase5-dev qtdeclarative5-dev libkf5coreaddons-dev libkf5i18n-dev libkf5config-dev libkf5dbusaddons-dev libkf5plasma-dev libkf5notifications-dev libkf5service-dev libkf5iconthemes-dev libkf5kio-dev gettext

    - name: Configure kded
      run: cmake -S . -B build

    - name: Build kded
      run: cmake --build build

    - name: Install kded (optional, for testing)
      run: sudo cmake --install build

    - name: Run Tests (optional)
      run: ctest --output-on-failure --test-dir build
      if: ${{ success() }}
