name: Build KDE Daemon (kded)

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main  # or your working branch
  pull_request:
    branches:
      - main  # or your working branch

jobs:
  build:
    runs-on: self-hosted

    

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo dnf install -y cmake gcc-c++ extra-cmake-modules qt5-qtbase-devel qt5-qtdeclarative-devel kf5-kcoreaddons-devel kf5-ki18n-devel kf5-kconfig-devel kf5-kdbusaddons-devel kf5-knotifications-devel kf5-kservice-devel kf5-kiconthemes-devel kf5-kio-devel gettext

    - name: Configure kded
      run: cmake -S . -B build

    - name: Build kded
      run: cmake --build build

    - name: Install kded (optional, for testing)
      run: sudo cmake --install build

    - name: Run Tests (optional)
      run: ctest --output-on-failure --test-dir build
      if: ${{ success() }}
